unsloth/chat_templates.py, unsloth/models/_utils.py
* Update save.py
* saving
* Update save.py
* Update save.py
* Update save.py
* Update save.py
* Update save.py
* Update save.py
* Update save.py
* Update save.py
* Update save.py
* Update save.py
* Update save.py
* Update save.py
* Update save.py
* Update __init__.py
* Update save.py
* Update save.py
* Update save.py
* save
* trainer
* spaces
* original
* Gemma
* Update pyproject.toml
* Update mapper.py
* Update fast_lora.py
* FastGemmaModel
* model_type
* Update llama.py
* Update llama.py
* Update gemma.py
* Update gemma.py
* Update gemma.py
* Update llama.py
* Update llama.py
* Update fast_lora.py
* Update llama.py
* Update llama.py
* Update cross_entropy_loss.py
* Update llama.py
* Update llama.py
* gemma
* Update llama.py
* Update llama.py
* Update llama.py
* Update llama.py
* Update …
=> Hotfix - fix DoRA, Gemma prompt template (#202)

unsloth/tokenizer_utils.py
=> Fix #603 handling of formatting_func in tokenizer_utils for assitant/chat/completion training 

README.md
One-character typo fix while reading.
=> README: Fix minor typo.

unsloth/save.py
=> Revert "Fix breaking bug in save.py with interpreting quantization_method as a string when saving to gguf"

unsloth/save.py
=> Revert "Revert "Fix breaking bug in save.py with interpreting quantization_method as a string when saving to gguf""

README.md
Added instruction to Readme on setting up an pascal supported environment.
=> pascal support

unsloth/models/llama.py
In unsloth/unsloth/models/llama.py:
We added few lines of codes to provide more flexibility to users to customize their attentions in llama when using lora.
=> Providing more flexibility for users to customize their llama when using LoRA

unsloth/models/llama.py, unsloth/models/loader.py, unsloth/save.py, unsloth/tokenizer_utils.py
This PR will update token retrieval logic for unsloth to use the HF standard method.
This has a lot of advantages such as reading the token from colab secrets or from a config file.
Regards
Lain 
OSS Contributor
=> update token retrieval logic

unsloth/save.py
Hi there, 
I opened an issue earlier this morning and I have fixed it in my local version.
Let me know if this makes sense to you!
Fixes #1118.
Reviewer: @danielhanchen.
Best,
Giulia
=> Handle absolute paths for save_to_gguf using pathlib

unsloth/save.py
Hi there,
as promised, here is the PR!
Fixes #1119.
Reviewer: @danielhanchen.
Best,
Giulia
=> Only remove folder in sentencepiece check if it was created

unsloth/__init__.py, unsloth/chat_templates.py, unsloth/models/llama.py, unsloth/save.py
Remove extraneous `f` prefixes
=> Remove extraneous f prefixes

CONTRIBUTING.md, unsloth/models/_utils.py, unsloth/models/loader.py
Unsloth actually printing a lot of stuff in the background which I assume for debugging purposes
By being able to optionally disable the disable of printing, it would be very helpful for developers to debug the code (which is my own experience)
=> Improve debugging experience

unsloth/models/granite.py, unsloth/models/llama.py
Minor fix for 4.47.1 transformers in llama class and granite model's config appears slightly different than in prior versions, the residual mult is now directly on layer
=> Minor fixes for granite models

pyproject.toml, unsloth/__init__.py
hi there, I've just added two prints that say triton and Torch.Cuda is not available,( I was dumb and tried running it for about 6 hours on my Mac til I figured out the problem was about my M3 Mac that doesn't have a GPU :) )
please consider adding that, thanks
=> Torch.Cuda Is Available Condition and Warning

unsloth/models/_utils.py
See: https://github.com/unslothai/unsloth/issues/1555
=> fix: flash_attn_detection_error

unsloth/models/loader.py
Fixes https://github.com/unslothai/unsloth/issues/1948
=> Don't use revision when loading model_config and is_peft=True

unsloth/models/_utils.py, unsloth/models/loader.py, unsloth/models/rl.py, unsloth/tokenizer_utils.py
```bash
flake8 2> /dev/null | grep escape
```
=> More syntax warnings

unsloth/models/llama.py
=> fix: config.torch_dtype in LlamaModel_fast_forward_inference

unsloth/save.py
Reverts unslothai/unsloth#2358
=> Revert "fix: improved error handling when llama.cpp build fails"

unsloth/models/_utils.py, unsloth/models/llama.py, unsloth/models/qwen3.py
Couple of minor fixes to get qwen3 working on unsloth
Will do extensive testing today and work on the rest...
=> Fixup qwen3

unsloth/models/loader.py
For now we turn off compile and fast generation for sesame csm.
=> Add Sesame CSM

tests/saving/language_models/test_merge_model_perplexity_llama-3.2.py, tests/saving/language_models/test_merge_model_perplexity_mistral.py, tests/saving/language_models/test_merge_model_perplexity_phi_4.py, tests/saving/language_models/test_merged_model_perplexity_llama-3.1-8b.py, tests/saving/language_models/test_merged_model_perplexity_qwen_2.5.py, tests/saving/language_models/test_push_to_hub_merged.py, tests/saving/language_models/test_push_to_hub_merged_sharded_index_file.py, tests/saving/language_models/test_save_merged_grpo_model.py, tests/saving/non_peft/test_mistral_non_peft.py, tests/saving/non_peft/test_whisper_non_peft.py, tests/saving/text_to_speech_models/test_csm.py, tests/saving/text_to_speech_models/test_lasa.py, tests/saving/text_to_speech_models/test_orpheus.py, tests/saving/text_to_speech_models/test_whisper.py, tests/saving/vision_models/test_index_file_sharded_model.py, tests/saving/vision_models/test_push_to_hub_merged.py, tests/saving/vision_models/test_save_merge_vision_model_ocr_benchmark.py, tests/utils/os_utils.py
Tests for unsloth-zoo PR [#163](https://github.com/unslothai/unsloth-zoo/pull/163) - Additional fixes to merge logic
=> tests for additional merge fix unsloth zoo pr 163

unsloth/__init__.py, unsloth/models/llama.py, unsloth/models/rl_replacements.py
Needs corresponding unsloth-zoo PR: unslothai/unsloth-zoo#162
=> Enable vLLM to share memory space

unsloth/models/rl_replacements.py
Final `_prepare_inputs` after the changes
=> Fix grpo sleep regex and indentation

unsloth/models/loader.py
This pr adds support for granite4 hybrid mamba moe architectures
=> Granite4 support

unsloth/models/loader.py
Route to fastmodel for falcon h1.
=> use fastmodel falcon h1

unsloth/models/_utils.py, unsloth/models/loader.py, unsloth/models/vision.py
**Key Changes:**
* **`models/loader.py`** – Added `trust_remote_code` support for LoRA loading
* **`models/_utils.py`** – Fixed [[#3048](https://github.com/unslothai/unsloth/issues/3048)](https://github.com/unslothai/unsloth/issues/3048) and improved loading when using `auto_model=AutoModelForSequenceClassification`
* **`models/vision.py`** – Added check for `target_modules` if it's a `str` (for regex support)
=> Bug Fixes and Enhancements for Model Loading

unsloth/models/loader.py
This PR will use the Gemma3n patch created by https://github.com/unslothai/unsloth-zoo/pull/291/files
Notebook test:
https://colab.research.google.com/drive/1-oBw1HoovFeI-NfVFZPaVsKP7Amj9z3l?usp=sharing
No errors but still nan issues to fix
=> Use gemma3n embedder patch + adjust FORCE_FLOAT32 match logic
